# Generated by Django 2.2 on 2020-05-30 10:27

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('name', models.CharField(max_length=20)),
                ('caption', models.TextField()),
            ],
        ),
    ]
