# Generated by Django 2.2 on 2020-06-01 10:09

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('name', models.CharField(max_length=20)),
                ('caption', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
