# Generated by Django 2.2 on 2020-05-31 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200531_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
