# Generated by Django 2.2 on 2020-05-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_image_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
    ]
